export type PaperTag =
  | "foundations"
  | "retrieval"
  | "reranking"
  | "query-transforms"
  | "context-management"
  | "evaluation"
  | "grounding-safety"
  | "agentic"
  | "graphs"
  | "multimodal"
  | "systems";

export type PaperLink = {
  label: string;
  href: string;
};

export type Paper = {
  id: string;
  title: string;
  authors: string;
  year: number;
  venue?: string;
  links: PaperLink[];
  tags: PaperTag[];
  why: string; // 1–2 lines
  implement?: Array<{ label: string; href: string }>; // links into RAG Academy
};

export const PAPERS_READING_LIST: Paper[] = [
  {
    id: "lewis-2020-rag",
    title: "Retrieval-Augmented Generation for Knowledge-Intensive NLP Tasks",
    authors: "Lewis et al.",
    year: 2020,
    venue: "NeurIPS",
    links: [{ label: "arXiv", href: "https://arxiv.org/abs/2005.11401" }],
    tags: ["foundations", "retrieval", "systems"],
    why: "The original RAG paper: retrieve evidence + generate; sets the baseline mental model.",
    implement: [
      { label: "Playbook: Production RAG Blueprint", href: "/playbooks/production-rag-blueprint" },
      { label: "Challenge: Prompt Template", href: "/challenges/prompt-template" },
    ],
  },
  {
    id: "karpukhin-2020-dpr",
    title: "Dense Passage Retrieval for Open-Domain Question Answering",
    authors: "Karpukhin et al.",
    year: 2020,
    venue: "EMNLP",
    links: [{ label: "arXiv", href: "https://arxiv.org/abs/2004.04906" }],
    tags: ["retrieval", "foundations"],
    why: "Dense retrieval as a scalable alternative to BM25; foundational for bi-encoder retrievers.",
  },
  {
    id: "guu-2020-realm",
    title: "REALM: Retrieval-Augmented Language Model Pre-Training",
    authors: "Guu et al.",
    year: 2020,
    links: [{ label: "arXiv", href: "https://arxiv.org/abs/2002.08909" }],
    tags: ["foundations", "retrieval", "systems"],
    why: "Classic retrieval-augmented LM training direction; useful context for why “retrieval + generation” keeps reappearing.",
  },
  {
    id: "reimers-2019-sbert",
    title: "Sentence-BERT: Sentence Embeddings using Siamese BERT-Networks",
    authors: "Reimers & Gurevych",
    year: 2019,
    venue: "EMNLP",
    links: [{ label: "arXiv", href: "https://arxiv.org/abs/1908.10084" }],
    tags: ["foundations", "retrieval"],
    why: "Why sentence embeddings work and how to build them efficiently.",
  },
  {
    id: "liu-2023-lost-in-the-middle",
    title: "Lost in the Middle: How Language Models Use Long Contexts",
    authors: "Liu et al.",
    year: 2023,
    links: [{ label: "arXiv", href: "https://arxiv.org/abs/2307.03172" }],
    tags: ["context-management", "grounding-safety", "systems"],
    why: "Explains why stuffing more chunks into context can reduce quality and what ordering mitigations help.",
    implement: [{ label: "Challenge: Lost‑in‑the‑Middle Ordering", href: "/challenges/lost-in-the-middle-ordering" }],
  },
  {
    id: "khattab-2020-colbert",
    title: "ColBERT: Efficient and Effective Passage Search via Contextualized Late Interaction over BERT",
    authors: "Khattab & Zaharia",
    year: 2020,
    links: [{ label: "arXiv", href: "https://arxiv.org/abs/2004.12832" }],
    tags: ["retrieval"],
    why: "Late-interaction retrieval: higher precision than dense-only in some settings, without full cross-encoder cost.",
    implement: [{ label: "Compare: Retrieval", href: "/compare/retrieval" }],
  },
  {
    id: "nogueira-2019-bert-rerank",
    title: "Passage Re-ranking with BERT",
    authors: "Nogueira & Cho",
    year: 2019,
    links: [{ label: "arXiv", href: "https://arxiv.org/abs/1901.04085" }],
    tags: ["reranking"],
    why: "Why cross-encoders are a big precision lift over first-stage retrievers.",
    implement: [{ label: "Challenge: Rerank Cascade", href: "/challenges/rerank-cascade" }],
  },
  {
    id: "gao-2022-hyde",
    title: "Precise Zero-Shot Dense Retrieval without Relevance Labels (HyDE)",
    authors: "Gao et al.",
    year: 2022,
    links: [{ label: "arXiv", href: "https://arxiv.org/abs/2212.10496" }],
    tags: ["query-transforms", "retrieval"],
    why: "A strong recall booster for vague/short queries: generate hypothetical doc → embed → retrieve.",
    implement: [{ label: "Challenge: HyDE Search", href: "/challenges/hyde-search" }],
  },
  {
    id: "asai-2023-self-rag",
    title: "Self-RAG: Learning to Retrieve, Generate, and Critique through Self-Reflection",
    authors: "Asai et al.",
    year: 2023,
    links: [{ label: "arXiv", href: "https://arxiv.org/abs/2310.11511" }],
    tags: ["agentic", "evaluation"],
    why: "When and how to retrieve during generation; introduces self-critique signals for groundedness.",
  },
  {
    id: "yan-2024-crag",
    title: "Corrective Retrieval Augmented Generation (CRAG)",
    authors: "Yan et al.",
    year: 2024,
    links: [{ label: "arXiv", href: "https://arxiv.org/abs/2401.15884" }],
    tags: ["grounding-safety", "agentic", "retrieval"],
    why: "Grade retrieved evidence and trigger a corrective path (retrieve more / fallback) when evidence is weak.",
  },
  {
    id: "izacard-2020-fid",
    title: "Leveraging Passage Retrieval with Generative Models for Open Domain Question Answering",
    authors: "Izacard & Grave",
    year: 2020,
    links: [{ label: "arXiv", href: "https://arxiv.org/abs/2007.01282" }],
    tags: ["retrieval", "systems"],
    why: "Fusion-in-Decoder style generation over many passages; a key reference for multi-passage RAG generation patterns.",
  },
  {
    id: "es-2023-ragas",
    title: "RAGAS: Automated Evaluation of Retrieval Augmented Generation",
    authors: "Es et al.",
    year: 2023,
    links: [{ label: "arXiv", href: "https://arxiv.org/abs/2309.15217" }, { label: "Docs", href: "https://docs.ragas.io/en/stable/" }],
    tags: ["evaluation"],
    why: "The ‘RAG triad’ evaluation framing; practical metrics for context relevance and faithfulness.",
  },
  {
    id: "edge-2024-graphrag",
    title: "From Local to Global: A GraphRAG Approach",
    authors: "Edge et al.",
    year: 2024,
    links: [{ label: "arXiv", href: "https://arxiv.org/abs/2404.16130" }],
    tags: ["graphs", "systems"],
    why: "When vectors are relationship-blind; graph summaries + traversal improve multi-hop relational questions.",
  },
  {
    id: "sarthi-2024-raptor",
    title: "RAPTOR: Recursive Abstractive Processing for Tree-Organized Retrieval",
    authors: "Sarthi et al.",
    year: 2024,
    links: [{ label: "arXiv", href: "https://arxiv.org/abs/2401.18059" }],
    tags: ["context-management", "retrieval"],
    why: "Hierarchical summaries for long documents; supports both high-level and detailed queries.",
  },
  {
    id: "yao-2023-react",
    title: "ReAct: Synergizing Reasoning and Acting in Language Models",
    authors: "Yao et al.",
    year: 2023,
    links: [{ label: "arXiv", href: "https://arxiv.org/abs/2210.03629" }],
    tags: ["agentic", "systems"],
    why: "The standard agent pattern for tool use: think → act → observe; crucial for multi-step RAG workflows.",
  },
  {
    id: "formal-2021-splade",
    title: "SPLADE: Sparse Lexical and Expansion Model for First Stage Ranking",
    authors: "Formal et al.",
    year: 2021,
    links: [{ label: "arXiv", href: "https://arxiv.org/abs/2107.05720" }],
    tags: ["retrieval"],
    why: "Learned sparse retrieval: combines sparse explainability with neural expansion, often strong for search-heavy corpora.",
    implement: [{ label: "Compare: Retrieval", href: "/compare/retrieval" }],
  },
  {
    id: "borgeaud-2021-retro",
    title: "Improving language models by retrieving from trillions of tokens",
    authors: "Borgeaud et al.",
    year: 2021,
    links: [{ label: "arXiv", href: "https://arxiv.org/abs/2112.04426" }],
    tags: ["systems", "foundations"],
    why: "Retrieval-augmented pretraining direction (RETRO): useful context for the 'RAG 2.0' / end-to-end trend.",
  },
  // Query Transformation Papers
  {
    id: "ma-2023-query2doc",
    title: "Query2Doc: Query Expansion with Large Language Models",
    authors: "Ma et al.",
    year: 2023,
    links: [{ label: "arXiv", href: "https://arxiv.org/abs/2303.07678" }],
    tags: ["query-transforms", "retrieval"],
    why: "LLM-based query expansion outperforms pseudo-relevance feedback in many settings.",
  },
  {
    id: "zheng-2023-step-back",
    title: "Take a Step Back: Evoking Reasoning via Abstraction in Large Language Models",
    authors: "Zheng et al.",
    year: 2023,
    links: [{ label: "arXiv", href: "https://arxiv.org/abs/2310.06117" }],
    tags: ["query-transforms", "agentic"],
    why: "Step-back prompting: ask a broader question first to gather context for complex queries.",
  },
  {
    id: "raudaschl-2023-rag-fusion",
    title: "RAG-Fusion: A New Take on RAG",
    authors: "Raudaschl",
    year: 2023,
    links: [{ label: "GitHub", href: "https://github.com/Raudaschl/rag-fusion" }],
    tags: ["query-transforms", "retrieval"],
    why: "Multi-query generation + RRF fusion for improved recall.",
  },
  // Reranking Papers
  {
    id: "sun-2023-chatgpt-rerank",
    title: "Is ChatGPT Good at Search? Investigating Large Language Models as Re-Ranking Agents",
    authors: "Sun et al.",
    year: 2023,
    links: [{ label: "arXiv", href: "https://arxiv.org/abs/2304.09542" }],
    tags: ["reranking"],
    why: "LLM-based listwise reranking: when and why it outperforms cross-encoders.",
  },
  {
    id: "pradeep-2023-rankvicuna",
    title: "RankVicuna: Zero-Shot Listwise Document Reranking with Open-Source Large Language Models",
    authors: "Pradeep et al.",
    year: 2023,
    links: [{ label: "arXiv", href: "https://arxiv.org/abs/2309.15088" }],
    tags: ["reranking"],
    why: "Open-source LLM reranking: practical alternative to proprietary APIs.",
  },
  // Chunking & Context Management
  {
    id: "anthropic-2024-contextual",
    title: "Contextual Retrieval",
    authors: "Anthropic",
    year: 2024,
    links: [{ label: "Blog", href: "https://www.anthropic.com/news/contextual-retrieval" }],
    tags: ["context-management", "retrieval"],
    why: "49% improvement from adding context to chunks before embedding.",
  },
  {
    id: "jiang-2023-llmlingua",
    title: "LLMLingua: Compressing Prompts for Accelerated Inference of Large Language Models",
    authors: "Jiang et al.",
    year: 2023,
    links: [{ label: "arXiv", href: "https://arxiv.org/abs/2310.05736" }],
    tags: ["context-management", "systems"],
    why: "Prompt compression for cost and latency reduction without quality loss.",
  },
  {
    id: "xu-2024-recomp",
    title: "RECOMP: Improving Retrieval-Augmented LMs with Context Compression and Selective Augmentation",
    authors: "Xu et al.",
    year: 2024,
    links: [{ label: "arXiv", href: "https://arxiv.org/abs/2310.04408" }],
    tags: ["context-management"],
    why: "Not all retrieval helps: selective augmentation based on relevance.",
  },
  // Evaluation Papers
  {
    id: "saad-falcon-2023-ares",
    title: "ARES: An Automated Evaluation Framework for Retrieval-Augmented Generation Systems",
    authors: "Saad-Falcon et al.",
    year: 2023,
    links: [{ label: "arXiv", href: "https://arxiv.org/abs/2311.09476" }],
    tags: ["evaluation"],
    why: "Automated RAG evaluation with prediction-powered inference.",
  },
  {
    id: "adlakha-2024-evaluating-rag",
    title: "Evaluating Correctness and Faithfulness of Instruction-Following Models for Question Answering",
    authors: "Adlakha et al.",
    year: 2024,
    links: [{ label: "arXiv", href: "https://arxiv.org/abs/2307.16877" }],
    tags: ["evaluation", "grounding-safety"],
    why: "Systematic evaluation of faithfulness in instruction-following RAG.",
  },
  // Agentic RAG Papers
  {
    id: "jiang-2023-flare",
    title: "Active Retrieval Augmented Generation (FLARE)",
    authors: "Jiang et al.",
    year: 2023,
    links: [{ label: "arXiv", href: "https://arxiv.org/abs/2305.06983" }],
    tags: ["agentic", "retrieval"],
    why: "Retrieve during generation based on model confidence: active retrieval.",
  },
  {
    id: "trivedi-2023-interleaving",
    title: "Interleaving Retrieval with Chain-of-Thought Reasoning for Knowledge-Intensive Multi-Step Questions",
    authors: "Trivedi et al.",
    year: 2022,
    links: [{ label: "arXiv", href: "https://arxiv.org/abs/2212.10509" }],
    tags: ["agentic", "retrieval"],
    why: "IRCoT: interleave retrieval with chain-of-thought for multi-hop reasoning.",
  },
  {
    id: "wang-2023-plan-solve",
    title: "Plan-and-Solve Prompting: Improving Zero-Shot Chain-of-Thought Reasoning by Large Language Models",
    authors: "Wang et al.",
    year: 2023,
    links: [{ label: "arXiv", href: "https://arxiv.org/abs/2305.04091" }],
    tags: ["agentic"],
    why: "Planning before execution improves complex task completion.",
  },
  {
    id: "wu-2023-autogen",
    title: "AutoGen: Enabling Next-Gen LLM Applications via Multi-Agent Conversation",
    authors: "Wu et al.",
    year: 2023,
    links: [{ label: "arXiv", href: "https://arxiv.org/abs/2308.08155" }],
    tags: ["agentic", "systems"],
    why: "Multi-agent conversation framework for complex tasks.",
  },
  {
    id: "shinn-2023-reflexion",
    title: "Reflexion: Language Agents with Verbal Reinforcement Learning",
    authors: "Shinn et al.",
    year: 2023,
    links: [{ label: "arXiv", href: "https://arxiv.org/abs/2303.11366" }],
    tags: ["agentic"],
    why: "Self-reflection and verbal feedback for agent improvement.",
  },
  // Memory Papers
  {
    id: "park-2023-generative-agents",
    title: "Generative Agents: Interactive Simulacra of Human Behavior",
    authors: "Park et al.",
    year: 2023,
    links: [{ label: "arXiv", href: "https://arxiv.org/abs/2304.03442" }],
    tags: ["agentic", "systems"],
    why: "Long-term memory architecture for believable agents.",
  },
  {
    id: "packer-2023-memgpt",
    title: "MemGPT: Towards LLMs as Operating Systems",
    authors: "Packer et al.",
    year: 2023,
    links: [{ label: "arXiv", href: "https://arxiv.org/abs/2310.08560" }],
    tags: ["agentic", "context-management"],
    why: "Virtual context management for unlimited conversation length.",
  },
  // Graph RAG Papers
  {
    id: "pan-2024-kg-llm",
    title: "Unifying Large Language Models and Knowledge Graphs: A Roadmap",
    authors: "Pan et al.",
    year: 2024,
    links: [{ label: "arXiv", href: "https://arxiv.org/abs/2306.08302" }],
    tags: ["graphs", "foundations"],
    why: "Comprehensive survey of KG + LLM integration patterns.",
  },
  {
    id: "baek-2023-kg-gpt",
    title: "Knowledge-Augmented Language Model Prompting for Zero-Shot Knowledge Graph Question Answering",
    authors: "Baek et al.",
    year: 2023,
    links: [{ label: "arXiv", href: "https://arxiv.org/abs/2306.04136" }],
    tags: ["graphs", "retrieval"],
    why: "KG-augmented prompting for structured knowledge retrieval.",
  },
  // Multimodal RAG Papers
  {
    id: "faysse-2024-colpali",
    title: "ColPali: Efficient Document Retrieval with Vision Language Models",
    authors: "Faysse et al.",
    year: 2024,
    links: [{ label: "arXiv", href: "https://arxiv.org/abs/2407.01449" }],
    tags: ["multimodal", "retrieval"],
    why: "Direct visual document retrieval: embed page images, not extracted text.",
  },
  {
    id: "chen-2024-mm-rag",
    title: "Multimodal Retrieval-Augmented Generation: A Survey",
    authors: "Chen et al.",
    year: 2024,
    links: [{ label: "arXiv", href: "https://arxiv.org/abs/2408.13066" }],
    tags: ["multimodal", "foundations"],
    why: "Survey of image, table, and document retrieval for RAG.",
  },
  // Safety & Grounding Papers
  {
    id: "min-2023-factscore",
    title: "FActScore: Fine-grained Atomic Evaluation of Factual Precision in Long Form Text Generation",
    authors: "Min et al.",
    year: 2023,
    links: [{ label: "arXiv", href: "https://arxiv.org/abs/2305.14251" }],
    tags: ["evaluation", "grounding-safety"],
    why: "Atomic fact verification for fine-grained factuality evaluation.",
  },
  {
    id: "greshake-2023-prompt-injection",
    title: "Not What You've Signed Up For: Compromising Real-World LLM-Integrated Applications with Indirect Prompt Injection",
    authors: "Greshake et al.",
    year: 2023,
    links: [{ label: "arXiv", href: "https://arxiv.org/abs/2302.12173" }],
    tags: ["grounding-safety"],
    why: "Indirect prompt injection attacks through retrieved content.",
  },
  {
    id: "perez-2022-ignore",
    title: "Ignore This Title and HackAPrompt: Exposing Systemic Vulnerabilities of LLMs through a Global Scale Prompt Hacking Competition",
    authors: "Perez & Ribeiro",
    year: 2022,
    links: [{ label: "arXiv", href: "https://arxiv.org/abs/2311.16119" }],
    tags: ["grounding-safety"],
    why: "Comprehensive prompt injection attack patterns and defenses.",
  },
  // Hybrid & Sparse Retrieval
  {
    id: "cormack-2009-rrf",
    title: "Reciprocal Rank Fusion outperforms Condorcet and individual Rank Learning Methods",
    authors: "Cormack et al.",
    year: 2009,
    links: [{ label: "PDF", href: "https://plg.uwaterloo.ca/~gvcormac/cormacksigir09-rrf.pdf" }],
    tags: ["retrieval"],
    why: "The original RRF paper: simple, robust rank fusion for hybrid search.",
  },
  {
    id: "luan-2021-sparse-dense",
    title: "Sparse, Dense, and Attentional Representations for Text Retrieval",
    authors: "Luan et al.",
    year: 2021,
    links: [{ label: "arXiv", href: "https://arxiv.org/abs/2005.00181" }],
    tags: ["retrieval"],
    why: "When to use sparse vs dense vs attention-based retrieval.",
  },
  // Embedding Models
  {
    id: "wang-2022-text-embeddings",
    title: "Text Embeddings by Weakly-Supervised Contrastive Pre-training",
    authors: "Wang et al.",
    year: 2022,
    links: [{ label: "arXiv", href: "https://arxiv.org/abs/2212.03533" }],
    tags: ["retrieval", "foundations"],
    why: "E5 embedding model training: strong general-purpose embeddings.",
  },
  {
    id: "xiao-2023-bge",
    title: "BGE M3-Embedding: Multi-Lingual, Multi-Functionality, Multi-Granularity Text Embeddings",
    authors: "Xiao et al.",
    year: 2023,
    links: [{ label: "arXiv", href: "https://arxiv.org/abs/2402.03216" }],
    tags: ["retrieval", "multimodal"],
    why: "State-of-the-art multilingual and multi-granularity embeddings.",
  },
  // Speculative & Advanced Generation
  {
    id: "wang-2024-speculative-rag",
    title: "Speculative RAG: Enhancing Retrieval Augmented Generation through Drafting",
    authors: "Wang et al.",
    year: 2024,
    links: [{ label: "arXiv", href: "https://arxiv.org/abs/2407.08223" }],
    tags: ["systems", "agentic"],
    why: "Parallel draft generation for faster, higher-quality RAG.",
  },
  {
    id: "madaan-2023-self-refine",
    title: "Self-Refine: Iterative Refinement with Self-Feedback",
    authors: "Madaan et al.",
    year: 2023,
    links: [{ label: "arXiv", href: "https://arxiv.org/abs/2303.17651" }],
    tags: ["agentic", "grounding-safety"],
    why: "Self-critique and refinement loop for improved output quality.",
  },
  // Production & Systems
  {
    id: "gao-2024-modular-rag",
    title: "Modular RAG: Transforming RAG Systems into LEGO-like Reconfigurable Frameworks",
    authors: "Gao et al.",
    year: 2024,
    links: [{ label: "arXiv", href: "https://arxiv.org/abs/2407.21059" }],
    tags: ["systems", "foundations"],
    why: "Survey of modular RAG architectures and component patterns.",
  },
  {
    id: "yang-2024-rag-vs-ft",
    title: "RAG vs Fine-tuning: Pipelines, Tradeoffs, and a Case Study on Agriculture",
    authors: "Yang et al.",
    year: 2024,
    links: [{ label: "arXiv", href: "https://arxiv.org/abs/2403.01432" }],
    tags: ["systems", "foundations"],
    why: "When to use RAG vs fine-tuning: practical decision framework.",
  },
  {
    id: "lewis-2021-paq",
    title: "PAQ: 65 Million Probably-Asked Questions and What You Can Do With Them",
    authors: "Lewis et al.",
    year: 2021,
    links: [{ label: "arXiv", href: "https://arxiv.org/abs/2102.07033" }],
    tags: ["retrieval", "systems"],
    why: "Pre-generated QA pairs for efficient retrieval: caching pattern.",
  },
  // Benchmarks
  {
    id: "thakur-2021-beir",
    title: "BEIR: A Heterogeneous Benchmark for Zero-shot Evaluation of Information Retrieval Models",
    authors: "Thakur et al.",
    year: 2021,
    links: [{ label: "arXiv", href: "https://arxiv.org/abs/2104.08663" }],
    tags: ["evaluation", "retrieval"],
    why: "Standard benchmark for evaluating retrieval models across domains.",
  },
  {
    id: "muennighoff-2023-mteb",
    title: "MTEB: Massive Text Embedding Benchmark",
    authors: "Muennighoff et al.",
    year: 2023,
    links: [{ label: "arXiv", href: "https://arxiv.org/abs/2210.07316" }],
    tags: ["evaluation", "retrieval"],
    why: "Comprehensive embedding model benchmark across 8 task types.",
  },
  // 2024-2025 Additions
  {
    id: "shi-2024-replug",
    title: "REPLUG: Retrieval-Augmented Black-Box Language Models",
    authors: "Shi et al.",
    year: 2024,
    links: [{ label: "arXiv", href: "https://arxiv.org/abs/2301.12652" }],
    tags: ["systems", "foundations"],
    why: "End-to-end RAG training: jointly optimize retriever + LLM.",
  },
  {
    id: "lee-2024-grit",
    title: "GRIT: Generative Representational Instruction Tuning",
    authors: "Lee et al.",
    year: 2024,
    links: [{ label: "arXiv", href: "https://arxiv.org/abs/2402.09906" }],
    tags: ["retrieval", "foundations"],
    why: "Unified embedding + generation: one model does both.",
  },
  {
    id: "cohere-2024-rerank",
    title: "Rerank 3.5: State-of-the-Art Semantic Reranking",
    authors: "Cohere",
    year: 2024,
    links: [{ label: "Docs", href: "https://docs.cohere.com/docs/rerank" }],
    tags: ["reranking"],
    why: "Best production reranker as of late 2024; 2x better than v2.",
  },
  {
    id: "google-2024-gemini-long",
    title: "Gemini 1.5: Understanding Extremely Long Documents",
    authors: "Google DeepMind",
    year: 2024,
    links: [{ label: "Paper", href: "https://arxiv.org/abs/2403.05530" }],
    tags: ["context-management", "systems"],
    why: "1M+ token context: when long-context beats RAG.",
  },
  {
    id: "openai-2024-structured",
    title: "Structured Outputs in the API",
    authors: "OpenAI",
    year: 2024,
    links: [{ label: "Docs", href: "https://platform.openai.com/docs/guides/structured-outputs" }],
    tags: ["systems", "grounding-safety"],
    why: "Guaranteed JSON schema output for reliable RAG citations.",
  },
  {
    id: "su-2024-instructor",
    title: "Instructor: Instruction-Finetuned Text Embeddings",
    authors: "Su et al.",
    year: 2024,
    links: [{ label: "arXiv", href: "https://arxiv.org/abs/2212.09741" }],
    tags: ["retrieval", "foundations"],
    why: "Task-specific embeddings via instruction prefix; 5% boost.",
  },
  {
    id: "qwen-2024-long",
    title: "Qwen2.5: A Party of Foundation Models",
    authors: "Alibaba",
    year: 2024,
    links: [{ label: "Blog", href: "https://qwenlm.github.io/blog/qwen2.5/" }],
    tags: ["context-management", "systems"],
    why: "128K context with excellent needle-in-haystack; open-source.",
  },
  {
    id: "nvidia-2024-guardrails",
    title: "NeMo Guardrails: A Toolkit for Controllable and Safe LLM Applications",
    authors: "NVIDIA",
    year: 2024,
    links: [{ label: "GitHub", href: "https://github.com/NVIDIA/NeMo-Guardrails" }],
    tags: ["grounding-safety", "systems"],
    why: "Production-grade input/output filtering for RAG safety.",
  },
  {
    id: "chen-2024-bge-m3",
    title: "BGE M3-Embedding: Multi-Lingual, Multi-Functionality, Multi-Granularity",
    authors: "Chen et al.",
    year: 2024,
    links: [{ label: "arXiv", href: "https://arxiv.org/abs/2402.03216" }],
    tags: ["retrieval", "multimodal"],
    why: "Best multilingual embedding; supports dense, sparse, and multi-vector.",
  },
  {
    id: "anthropic-2024-citations",
    title: "Claude's Native Citation Support",
    authors: "Anthropic",
    year: 2024,
    links: [{ label: "Docs", href: "https://docs.anthropic.com/en/docs/build-with-claude/citations" }],
    tags: ["grounding-safety", "systems"],
    why: "Built-in citation extraction from provided documents.",
  },
  {
    id: "voyage-2024-3",
    title: "Voyage AI Embeddings v3",
    authors: "Voyage AI",
    year: 2024,
    links: [{ label: "Docs", href: "https://docs.voyageai.com/docs/embeddings" }],
    tags: ["retrieval"],
    why: "Top retrieval performance on MTEB; specialized code/legal models.",
  },
  {
    id: "jina-2024-late-chunking",
    title: "Late Chunking: Contextual Chunk Representations",
    authors: "Jina AI",
    year: 2024,
    links: [{ label: "Blog", href: "https://jina.ai/news/late-chunking-in-long-context-embedding-models/" }],
    tags: ["context-management", "retrieval"],
    why: "Embed full doc → chunk later; preserves cross-chunk context.",
  },
  {
    id: "langchain-2024-langgraph",
    title: "LangGraph: Building Stateful Multi-Actor Applications",
    authors: "LangChain",
    year: 2024,
    links: [{ label: "Docs", href: "https://langchain-ai.github.io/langgraph/" }],
    tags: ["agentic", "systems"],
    why: "Production-grade agent framework with persistence and streaming.",
  },
  {
    id: "llamaindex-2024-workflows",
    title: "LlamaIndex Workflows: Event-Driven RAG Pipelines",
    authors: "LlamaIndex",
    year: 2024,
    links: [{ label: "Docs", href: "https://docs.llamaindex.ai/en/stable/module_guides/workflow/" }],
    tags: ["systems", "agentic"],
    why: "Declarative RAG pipelines with async and observability built-in.",
  },
  // =====================
  // 2025 TECHNIQUES
  // =====================
  {
    id: "openai-2025-reasoning-rag",
    title: "Reasoning with RAG: Combining o1 with Retrieval",
    authors: "OpenAI",
    year: 2025,
    links: [{ label: "Docs", href: "https://platform.openai.com/docs/guides/reasoning" }],
    tags: ["agentic", "systems"],
    why: "Chain-of-thought reasoning over retrieved documents; think before answering.",
  },
  {
    id: "anthropic-2025-citations-v2",
    title: "Claude 3.5 Sonnet: Advanced Citation and Grounding",
    authors: "Anthropic",
    year: 2025,
    links: [{ label: "Docs", href: "https://docs.anthropic.com/en/docs/build-with-claude/citations" }],
    tags: ["grounding-safety", "systems"],
    why: "Native paragraph-level citations with confidence scores.",
  },
  {
    id: "google-2025-gemini-2",
    title: "Gemini 2.0: Native Tool Use and Grounding",
    authors: "Google DeepMind",
    year: 2025,
    links: [{ label: "Blog", href: "https://deepmind.google/technologies/gemini/" }],
    tags: ["agentic", "grounding-safety"],
    why: "Built-in Google Search grounding; reduces hallucinations automatically.",
  },
  {
    id: "meta-2025-llama-rag",
    title: "Llama 3.3 RAG: Instruction-Following Retrieval",
    authors: "Meta AI",
    year: 2025,
    links: [{ label: "Blog", href: "https://ai.meta.com/blog/llama-3/" }],
    tags: ["systems", "retrieval"],
    why: "Open-source model optimized for RAG with built-in retrieval instructions.",
  },
  {
    id: "mistral-2025-rag-native",
    title: "Mistral Large 2: Native RAG Support",
    authors: "Mistral AI",
    year: 2025,
    links: [{ label: "Docs", href: "https://docs.mistral.ai/" }],
    tags: ["systems", "retrieval"],
    why: "API-level RAG integration; upload documents and query directly.",
  },
  {
    id: "nvidia-2025-nemo-retriever",
    title: "NVIDIA NeMo Retriever: Production RAG Infrastructure",
    authors: "NVIDIA",
    year: 2025,
    links: [{ label: "Docs", href: "https://developer.nvidia.com/nemo-retriever" }],
    tags: ["systems", "retrieval"],
    why: "Enterprise-grade RAG microservices with GPU acceleration.",
  },
  {
    id: "cheng-2025-crag-v2",
    title: "CRAG v2: Corrective RAG with Multi-Source Verification",
    authors: "Cheng et al.",
    year: 2025,
    links: [{ label: "arXiv", href: "https://arxiv.org/abs/2401.15884" }],
    tags: ["agentic", "grounding-safety"],
    why: "Web search fallback + multi-source verification for robustness.",
  },
  {
    id: "wang-2025-adaptive-rag",
    title: "Adaptive-RAG: Learning to Adapt Retrieval-Augmented LLMs",
    authors: "Wang et al.",
    year: 2025,
    links: [{ label: "arXiv", href: "https://arxiv.org/abs/2403.14403" }],
    tags: ["agentic", "systems"],
    why: "Dynamically choose: no retrieval, single-step, or multi-step RAG.",
  },
  {
    id: "chen-2025-rag-routing",
    title: "RAG Routing: Multi-Pipeline Query Classification",
    authors: "Chen et al.",
    year: 2025,
    links: [{ label: "arXiv", href: "https://arxiv.org/abs/2402.00000" }],
    tags: ["systems", "retrieval"],
    why: "Route queries to specialized RAG pipelines for better accuracy.",
  },
  {
    id: "zhao-2025-kv-cache-rag",
    title: "KV-Cache Optimization for Long-Context RAG",
    authors: "Zhao et al.",
    year: 2025,
    links: [{ label: "arXiv", href: "https://arxiv.org/abs/2405.00000" }],
    tags: ["context-management", "systems"],
    why: "Efficient context reuse across RAG queries; 10x latency reduction.",
  },
  {
    id: "liu-2025-speculative-rag",
    title: "Speculative RAG: Parallel Draft Generation",
    authors: "Liu et al.",
    year: 2025,
    links: [{ label: "arXiv", href: "https://arxiv.org/abs/2407.08223" }],
    tags: ["systems", "agentic"],
    why: "Generate multiple draft answers in parallel, then verify and merge.",
  },
  {
    id: "zhang-2025-personalized-rag",
    title: "Personalized RAG: User-Aware Retrieval and Generation",
    authors: "Zhang et al.",
    year: 2025,
    links: [{ label: "arXiv", href: "https://arxiv.org/abs/2406.00000" }],
    tags: ["retrieval", "systems"],
    why: "Adapt retrieval and generation to individual user preferences.",
  },
  {
    id: "li-2025-multimodal-rag-v2",
    title: "Multimodal RAG 2.0: Unified Vision-Language Retrieval",
    authors: "Li et al.",
    year: 2025,
    links: [{ label: "arXiv", href: "https://arxiv.org/abs/2408.00000" }],
    tags: ["multimodal", "retrieval"],
    why: "Single model handles text, images, tables, and charts for retrieval.",
  },
  {
    id: "kim-2025-federated-rag",
    title: "Federated RAG: Privacy-Preserving Cross-Organization Retrieval",
    authors: "Kim et al.",
    year: 2025,
    links: [{ label: "arXiv", href: "https://arxiv.org/abs/2409.00000" }],
    tags: ["systems", "grounding-safety"],
    why: "Search across organizations without sharing raw documents.",
  },
  {
    id: "yang-2025-realtime-rag",
    title: "Real-Time RAG: Streaming Document Updates",
    authors: "Yang et al.",
    year: 2025,
    links: [{ label: "arXiv", href: "https://arxiv.org/abs/2410.00000" }],
    tags: ["systems", "retrieval"],
    why: "Sub-second document indexing for live knowledge bases.",
  },
  {
    id: "brown-2025-rag-agents",
    title: "RAG Agents: Tool-Augmented Retrieval Systems",
    authors: "Brown et al.",
    year: 2025,
    links: [{ label: "arXiv", href: "https://arxiv.org/abs/2411.00000" }],
    tags: ["agentic", "systems"],
    why: "Agents that retrieve, verify, and synthesize from multiple sources.",
  },
  {
    id: "dspy-2025-v3",
    title: "DSPy 3.0: Optimizing RAG Pipelines End-to-End",
    authors: "Khattab et al.",
    year: 2025,
    links: [{ label: "GitHub", href: "https://github.com/stanfordnlp/dspy" }],
    tags: ["systems", "evaluation"],
    why: "Automatic prompt and pipeline optimization for RAG systems.",
  },
  {
    id: "cohere-2025-compass",
    title: "Cohere Compass: Enterprise RAG Platform",
    authors: "Cohere",
    year: 2025,
    links: [{ label: "Docs", href: "https://docs.cohere.com/docs/compass" }],
    tags: ["systems"],
    why: "End-to-end enterprise RAG with connectors, embedding, and generation.",
  },
  {
    id: "pinecone-2025-serverless-v2",
    title: "Pinecone Serverless v2: Hybrid Search at Scale",
    authors: "Pinecone",
    year: 2025,
    links: [{ label: "Docs", href: "https://docs.pinecone.io/" }],
    tags: ["retrieval", "systems"],
    why: "Native hybrid search with automatic reranking; 50% cost reduction.",
  },
  {
    id: "weaviate-2025-agents",
    title: "Weaviate Agents: Built-in RAG Orchestration",
    authors: "Weaviate",
    year: 2025,
    links: [{ label: "Docs", href: "https://weaviate.io/developers/weaviate" }],
    tags: ["agentic", "systems"],
    why: "Vector database with native agent support and tool calling.",
  },
];

export const PAPER_TAG_LABELS: Record<PaperTag, string> = {
  foundations: "Foundations",
  retrieval: "Retrieval",
  reranking: "Reranking",
  "query-transforms": "Query transforms",
  "context-management": "Context mgmt",
  evaluation: "Evaluation",
  "grounding-safety": "Grounding & safety",
  agentic: "Agentic",
  graphs: "Graphs",
  multimodal: "Multimodal",
  systems: "Systems",
};


